<script lang="ts">
import {onMount} from 'svelte'; import {onAuthStateChanged,type User} from 'firebase/auth'; import {collection,doc,addDoc,updateDoc,onSnapshot,Timestamp} from 'firebase/firestore'; import {auth,db,firebaseConfigError} from './lib/firebase';  import {loginWithEmail,signupWithEmail,loginWithGoogle,logout} from './lib/services/firebase/auth'; import {addExpense,deleteExpense} from './lib/services/firebase/expenses'; import {addDebt,deleteDebt} from './lib/services/firebase/debts'; import {addRecurringExpense,deleteRecurringExpense} from './lib/services/firebase/recurring'; import {addMonthlyTask,deleteMonthlyTask,updateMonthlyTask} from './lib/services/firebase/tasks'; import {addCalendarEvent,deleteCalendarEvent} from './lib/services/firebase/calendar'; import {createListenerManager} from './lib/services/firebase/listeners';
type Section='dashboard'|'expenses'|'debts'|'recurring'|'tasks'|'calendar'; type Language='en'|'ru'|'az'|'it'; type RecordItem={id:string;name:string;amount:number;date:string;category:string;done:boolean;notes:string;status:string};
const copy:Record<Language,Record<string,string>>={
en:{dashboard:'Dashboard',expenses:'Expenses',debts:'Debts',recurring:'Recurring',tasks:'Tasks',calendar:'Calendar',add:'Add new',spent:'Spent this month',balance:'Outstanding debts',progress:'Task progress',events:'Upcoming events',save:'Save',cancel:'Cancel',delete:'Delete',complete:'Complete',signIn:'Sign in',register:'Register',welcome:'Your calm command centre',email:'Email',password:'Password',demo:'',name:'Name',amount:'Amount',date:'Date',category:'Category',notes:'Notes',empty:'Nothing here yet',calculator:'Calculator',shopping:'Shopping list',item:'Item',addItem:'Add item',clear:'Clear',light:'Light',dark:'Dark',offline:'',synced:'Firebase connected'},
ru:{dashboard:'\u041e\u0431\u0437\u043e\u0440',expenses:'\u0420\u0430\u0441\u0445\u043e\u0434\u044b',debts:'\u0414\u043e\u043b\u0433\u0438',recurring:'\u0420\u0435\u0433\u0443\u043b\u044f\u0440\u043d\u044b\u0435',tasks:'\u0417\u0430\u0434\u0430\u0447\u0438',calendar:'\u041a\u0430\u043b\u0435\u043d\u0434\u0430\u0440\u044c',add:'\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c',spent:'\u0420\u0430\u0441\u0445\u043e\u0434\u044b \u0437\u0430 \u043c\u0435\u0441\u044f\u0446',balance:'\u0414\u043e\u043b\u0433\u0438 \u043a \u043e\u043f\u043b\u0430\u0442\u0435',progress:'\u041f\u0440\u043e\u0433\u0440\u0435\u0441\u0441 \u0437\u0430\u0434\u0430\u0447',events:'\u041f\u0440\u0435\u0434\u0441\u0442\u043e\u044f\u0449\u0438\u0435 \u0441\u043e\u0431\u044b\u0442\u0438\u044f',save:'\u0421\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u044c',cancel:'\u041e\u0442\u043c\u0435\u043d\u0430',delete:'\u0423\u0434\u0430\u043b\u0438\u0442\u044c',complete:'\u0413\u043e\u0442\u043e\u0432\u043e',signIn:'\u0412\u043e\u0439\u0442\u0438',register:'\u0420\u0435\u0433\u0438\u0441\u0442\u0440\u0430\u0446\u0438\u044f',welcome:'\u0412\u0430\u0448 \u0446\u0435\u043d\u0442\u0440 \u0443\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u0438\u044f',email:'\u042d\u043b. \u043f\u043e\u0447\u0442\u0430',password:'\u041f\u0430\u0440\u043e\u043b',demo:'',name:'\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435',amount:'\u0421\u0443\u043c\u043c\u0430',date:'\u0414\u0430\u0442\u0430',category:'\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f',notes:'\u0417\u0430\u043c\u0435\u0442\u043a\u0438',empty:'\u0417\u0434\u0435\u0441\u044c \u043f\u043e\u043a\u0430 \u043d\u0438\u0447\u0435\u0433\u043e \u043d\u0435\u0442',calculator:'\u041a\u0430\u043b\u044c\u043a\u0443\u043b\u044f\u0442\u043e\u0440',shopping:'\u0421\u043f\u0438\u0441\u043e\u043a \u043f\u043e\u043a\u0443\u043f\u043e\u043a',item:'\u0422\u043e\u0432\u0430\u0440',addItem:'\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c',clear:'\u041e\u0447\u0438\u0441\u0442\u0438\u0442\u044c',light:'\u0421\u0432\u0435\u0442\u043b\u0430\u044f',dark:'\u0422\u0451\u043c\u043d\u0430\u044f',offline:'',synced:'Firebase \u043f\u043e\u0434\u043a\u043b\u044e\u0447\u0451\u043d'},
az:{dashboard:'dar paneli',expenses:'Xrclr',debts:'Borclar',recurring:'Tkrarlanan',tasks:'Taprqlar',calendar:'Tqvim',add:'lav et',spent:'Bu ay xrclr',balance:'Borclar',progress:'Taprq irlilyii',events:'Glck tdbirlr',save:'Yadda saxla',cancel:'Lv et',delete:'Sil',complete:'Tamamland',signIn:'Daxil ol',register:'Qeydiyyat',welcome:'daretm mrkziniz',email:'E-pot',password:'ifr',demo:'',name:'Ad',amount:'Mbl',date:'Tarix',category:'Kateqoriya',notes:'Qeydlr',empty:'Hl he n yoxdur',calculator:'Kalkulyator',shopping:'Al-veri siyahs',item:'Mhsul',addItem:'lav et',clear:'Tmizl',light:'ql',dark:'Qaranlq',offline:'',synced:'Firebase qoulub'},
it:{dashboard:'Dashboard',expenses:'Spese',debts:'Debiti',recurring:'Ricorrenti',tasks:'Attivit',calendar:'Calendario',add:'Aggiungi',spent:'Spese del mese',balance:'Debiti aperti',progress:'Progresso',events:'Eventi',save:'Salva',cancel:'Annulla',delete:'Elimina',complete:'Completato',signIn:'Accedi',register:'Registrati',welcome:'Il tuo centro di controllo',email:'Email',password:'Password',demo:'',name:'Nome',amount:'Importo',date:'Data',category:'Categoria',notes:'Note',empty:'Ancora nulla',calculator:'Calcolatrice',shopping:'Lista della spesa',item:'Articolo',addItem:'Aggiungi',clear:'Cancella',light:'Chiaro',dark:'Scuro',offline:'',synced:'Firebase connesso'}};
const icons:Record<Section,string>={dashboard:'home',expenses:'expense',debts:'debt',recurring:'repeat',tasks:'task',calendar:'calendar'}; const today=()=>new Date().toISOString().slice(0,10); const manager=createListenerManager();
let language:Language='en',dark=false,currency='AZN',section:Section='dashboard',signedIn=false,email='',password='',error=firebaseConfigError||'',modal:'record'|'calculator'|'shopping'|null=null,records:Record<Exclude<Section,'dashboard'>,RecordItem[]>={expenses:[],debts:[],recurring:[],tasks:[],calendar:[]},form={name:'',amount:'',date:today(),category:'General',notes:''},calculator='',shoppingInput='',shopping:{id:string;name:string;done:boolean}[]=[],toast='',now=new Date(),currentUser:User|null=null,categories:RecordItem[]=[];
$:t=(id:string)=>copy[language][id]||copy.en[id]||id; $:currency=currency; $:expensesTotal=records.expenses.reduce((n,x)=>n+(x.amount||0),0); $:debtTotal=records.debts.reduce((n,x)=>n+(x.amount||0),0); $:completeCount=records.tasks.filter(x=>x.done||x.status==='Выполнено').length; $:monthId=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`; $:monthLabel=new Intl.DateTimeFormat(language,{month:'long',year:'numeric'}).format(now); $:appClass=`app ${dark ? 'dark' : ''}`;
const money=(n:number)=>new Intl.NumberFormat(language,{style:'currency',currency,maximumFractionDigits:0}).format(n); function notify(m:string){toast=m;setTimeout(()=>toast='',2200)} function items(s:{docs:Array<{id:string;data:()=>Record<string,unknown>}>}){return s.docs.map(d=>({id:d.id,...d.data(),done:d.data().status==='Выполнено'||d.data().done===true} as RecordItem))}
function listen(uid:string){manager.detachAll();manager.attachExpensesListener(uid,monthId,s=>records={...records,expenses:items(s)});manager.attachMonthlyTasksListener(uid,monthId,s=>records={...records,tasks:items(s)});manager.attachDailyTasksListener(uid,today(),s=>records={...records,tasks:[...records.tasks,...items(s)]});manager.attachYearlyTasksListener(uid,now.getFullYear(),s=>records={...records,tasks:[...records.tasks,...items(s)]});manager.attachDebtsListener(uid,s=>records={...records,debts:items(s)});manager.attachRecurringExpensesListener(uid,s=>records={...records,recurring:items(s)});manager.attachRecurringExpenseStatusesListener(uid,monthId,()=>{});manager.attachCategoriesListener(uid,s=>categories=items(s));manager.attachCalendarEventsListener(uid,s=>records={...records,calendar:items(s)});onSnapshot(collection(db,'users',uid,'shoppingItems'),s=>shopping=s.docs.map(d=>({id:d.id,...d.data()} as {id:string;name:string;done:boolean})))}
async function enter(){if(firebaseConfigError)return;try{if(!email||!password)throw Error();await loginWithEmail(email,password)}catch{error='Unable to sign in.'}} async function signup(){if(firebaseConfigError)return;try{await signupWithEmail(email,password)}catch{error='Unable to register.'}} async function google(){if(firebaseConfigError)return;try{await loginWithGoogle()}catch{error='Unable to sign in with Google.'}}
function openRecord(target=section){section=target==='dashboard'?'expenses':target;form={name:'',amount:'',date:today(),category:'General',notes:''};modal='record'}
async function saveRecord(){if(!currentUser||!form.name.trim())return notify('Add a name first');try{const d={name:form.name.trim(),amount:Number(form.amount)||0,date:form.date,category:form.category,notes:form.notes};if(section==='expenses')await addExpense(currentUser.uid,monthId,d as never);else if(section==='debts')await addDebt(currentUser.uid,{name:d.name,totalAmount:d.amount,paidAmount:0,comment:d.notes} as never);else if(section==='recurring')await addRecurringExpense(currentUser.uid,{name:d.name,amount:d.amount,dueDay:Number(d.date.slice(-2))||1,details:d.notes} as never);else if(section==='tasks')await addMonthlyTask(currentUser.uid,monthId,{name:d.name,month:monthId,status:'\\u041d\\u0435 \\u0432\\u044b\\u043f\\u043e\\u043b\\u043d\\u0435\\u043d\\u043e',notes:d.notes,carriedOver:false} as never);else await addCalendarEvent(currentUser.uid,{name:d.name,date:d.date,type:'event',notes:d.notes} as never);modal=null;notify(t('save'))}catch{notify('Unable to save.')}}
async function removeRecord(target:Exclude<Section,'dashboard'>,id:string){if(!currentUser)return;try{if(target==='expenses')await deleteExpense(currentUser.uid,monthId,id);else if(target==='debts')await deleteDebt(currentUser.uid,id);else if(target==='recurring')await deleteRecurringExpense(currentUser.uid,id);else if(target==='tasks')await deleteMonthlyTask(currentUser.uid,monthId,id);else await deleteCalendarEvent(currentUser.uid,id);notify(t('delete'))}catch{notify('Unable to delete.')}} async function toggleTask(id:string){if(!currentUser)return;const x=records.tasks.find(y=>y.id===id);if(x)await updateMonthlyTask(currentUser.uid,monthId,id,{status:x.done?'?? ?????????':'?????????'} as never)}
async function toggleShopping(item:{id:string;done:boolean}){if(currentUser)await updateDoc(doc(db,'users',currentUser.uid,'shoppingItems',item.id),{done:!item.done})} function calculate(v:string){if(v==='C')calculator='';else calculator+=v} function setLanguage(v:Language){language=v} function selectLanguage(e:Event){setLanguage((e.currentTarget as HTMLSelectElement).value as Language)} function selectSection(v:string){if(v in icons)section=v as Section} function iconFor(v:string){return icons[v as Section]||''} async function addShopping(){if(currentUser&&shoppingInput.trim()){await addDoc(collection(db,'users',currentUser.uid,'shoppingItems'),{name:shoppingInput.trim(),done:false,createdAt:Timestamp.now()});shoppingInput=''}}
onMount(()=>{if(firebaseConfigError)return;const un=onAuthStateChanged(auth,u=>{currentUser=u;signedIn=!!u;if(u)listen(u.uid);else{manager.detachAll();records={expenses:[],debts:[],recurring:[],tasks:[],calendar:[]};shopping=[]}});const timer=setInterval(()=>now=new Date(),1000);return()=>{un();manager.detachAll();clearInterval(timer)}});
</script>


{#if !signedIn}
  <main class={appClass + ' auth-screen'}>
    <div class="loading-overlay" hidden aria-hidden="true"></div>
    <section class="auth-card">
      <div class="brand-mark">O</div><p class="eyebrow">LIFE ORDER ASSISTANT</p><h1>ORDINA</h1>
      <p class="muted">{t('welcome')}</p>
      <form on:submit|preventDefault={enter}>
        <label>{t('email')}<input bind:value={email} type="email" placeholder="you@example.com" /></label>
        <label>{t('password')}<input bind:value={password} type="password" minlength="6" placeholder="••••••••" /></label>
        {#if error}<p class="error">{error}</p>{/if}
        <button class="primary wide" type="submit" disabled={!!firebaseConfigError}>{t('signIn')}</button>
      </form>
      <button class="ghost wide" on:click={google} disabled={!!firebaseConfigError}>Continue with Google</button>
      <button class="text-button" on:click={signup} disabled={!!firebaseConfigError}>{t('register')}</button>
    </section>
  </main>
{:else}
  <div class={appClass}>
    <div class="ambient"><span></span><span></span><span></span></div>
    <header class="topbar">
      <button class="brand" on:click={() => section = 'dashboard'}><span class="brand-mark small">O</span><span><strong>ORDINA</strong><small>life, in order</small></span></button>
      <div class="top-widgets"><div class="mini-widget"><span>☼</span><strong>{now.getHours()}:{String(now.getMinutes()).padStart(2, '0')}</strong><small>{monthLabel}</small></div><div class="mini-widget"><span>☁</span><strong>22°</strong><small>Baku</small></div></div>
      <div class="top-actions"><button on:click={() => dark = !dark} aria-label="Toggle theme">{dark ? '☀' : '☾'}</button><select value={language} on:change={selectLanguage} aria-label="Language">{#each Object.keys(copy) as code}<option value={code}>{code.toUpperCase()}</option>{/each}</select><button on:click={() => currency = currency === 'AZN' ? 'USD' : 'AZN'}>{currency}</button><button on:click={() => logout()}>↪</button></div>
    </header>
    <div class="layout">
      <aside class="sidebar"><p class="nav-label">WORKSPACE</p>{#each Object.keys(icons) as item}<button class:active={section === item} on:click={() => selectSection(item)}><span class="nav-icon">{iconFor(item)}</span><span>{t(item)}</span></button>{/each}<div class="sidebar-bottom"><button on:click={() => modal = 'calculator'}>⌗ <span>{t('calculator')}</span></button><button on:click={() => modal = 'shopping'}>▣ <span>{t('shopping')}</span></button></div></aside>
      <main class="content">
        <div class="page-heading"><div><p class="eyebrow">{new Intl.DateTimeFormat(language, { weekday: 'long', month: 'long', day: 'numeric' }).format(now)}</p><h1>{t(section)}</h1></div>{#if section !== 'dashboard'}<button class="primary" on:click={() => openRecord()}>＋ {t('add')}</button>{/if}</div>
        {#if section === 'dashboard'}
          <section class="stats-grid"><article><span>{t('spent')}</span><strong>{money(expensesTotal)}</strong><small class="positive">{t('offline')}</small></article><article><span>{t('balance')}</span><strong>{money(debtTotal)}</strong><small>{records.debts.length} records</small></article><article><span>{t('progress')}</span><strong>{completeCount}/{records.tasks.length || 0}</strong><small>{records.tasks.length ? Math.round(completeCount / records.tasks.length * 100) : 0}%</small></article><article><span>{t('events')}</span><strong>{records.calendar.length}</strong><small>{monthLabel}</small></article></section>
          <div class="dashboard-grid"><section class="panel"><div class="panel-head"><div><p class="eyebrow">OVERVIEW</p><h2>{monthLabel}</h2></div><button class="icon-button" on:click={() => openRecord('expenses')}>＋</button></div><div class="bars">{#each Array(12) as _, index}<div class="bar-wrap"><div class="bar" style={`height:${Math.max(8, Math.min(100, expensesTotal ? (index === now.getMonth() ? 100 : 24) : 8))}%`}></div><small>{['J','F','M','A','M','J','J','A','S','O','N','D'][index]}</small></div>{/each}</div></section><section class="panel"><div class="panel-head"><h2>{t('tasks')}</h2><button class="icon-button" on:click={() => section = 'tasks'}>→</button></div>{#if records.tasks.length}{#each records.tasks.slice(0, 5) as task}<label class="task-row"><input type="checkbox" checked={task.done} on:change={() => toggleTask(task.id)} /><span class:done={task.done}>{task.name}</span></label>{/each}{:else}<p class="empty">{t('empty')}</p>{/if}</section></div>
          <div class="dashboard-grid lower"><section class="panel"><div class="panel-head"><h2>Markets</h2><span class="pill">LIVE</span></div><div class="market-row"><span>AZN / USD</span><strong>0.588</strong><em>+0.12%</em></div><div class="market-row"><span>BTC / USD</span><strong>$62,430</strong><em>+1.84%</em></div></section><section class="panel"><div class="panel-head"><h2>News & radio</h2><button class="icon-button" on:click={() => notify('Radio preview ready')}>▶</button></div><p class="empty">Curated updates will appear here when connected.</p></section></div>
        {:else}
          <section class="panel"><div class="panel-head"><h2>{t(section)}</h2><strong class="total">{section === 'expenses' ? money(expensesTotal) : section === 'debts' ? money(debtTotal) : records[section].length}</strong></div>{#if records[section].length}{#each records[section] as item}<div class="list-row">{#if section === 'tasks'}<input type="checkbox" checked={item.done} on:change={() => toggleTask(item.id)} />{/if}<div class="data-main"><strong class:done={item.done}>{item.name}</strong><small>{item.date || item.category || t('complete')}</small></div><button class="danger-link" on:click={() => removeRecord(section, item.id)}>{t('delete')}</button></div>{/each}{:else}<div class="empty large">{t('empty')}<br /><button class="text-button" on:click={() => openRecord()}>{t('add')}</button></div>{/if}</section>
        {/if}
      </main>
    </div>
  </div>
{/if}

{#if modal}
  <div class="modal-backdrop" role="presentation" on:click={(e) => e.target === e.currentTarget && (modal = null)}><section class="modal" role="dialog" aria-modal="true">
    <button class="modal-close" on:click={() => modal = null}>×</button>
    {#if modal === 'calculator'}<p class="eyebrow">QUICK TOOL</p><h2>{t('calculator')}</h2><input class="calculator-display" value={calculator} readonly /><div class="calculator-grid">{#each ['7','8','9','/','4','5','6','*','1','2','3','-','0','.','C','='] as value}<button on:click={() => calculate(value)}>{value}</button>{/each}</div>
    {:else if modal === 'shopping'}<p class="eyebrow">QUICK TOOL</p><h2>{t('shopping')}</h2><div class="shopping-add"><input bind:value={shoppingInput} placeholder={t('item')} on:keydown={(e) => e.key === 'Enter' && addShopping()} /><button class="primary" on:click={addShopping}>{t('addItem')}</button></div>{#each shopping as item}<label class="task-row"><input type="checkbox" checked={item.done} on:change={() => toggleShopping(item)} /><span class:done={item.done}>{item.name}</span></label>{/each}
    {:else}<p class="eyebrow">NEW RECORD</p><h2>{t('add')} · {t(section)}</h2><form on:submit|preventDefault={saveRecord}><label>{t('name')}<input bind:value={form.name} required /></label>{#if section !== 'tasks' && section !== 'calendar'}<label>{t('amount')}<input type="number" min="0" step="0.01" bind:value={form.amount} /></label>{/if}<label>{t('date')}<input type="date" bind:value={form.date} /></label><label>{t('category')}<input bind:value={form.category} /></label><label>{t('notes')}<textarea bind:value={form.notes} rows="2"></textarea></label><button class="primary wide" type="submit">{t('save')}</button></form>{/if}
  </section></div>
{/if}
{#if toast}<div class="toast" role="status">{toast}</div>{/if}
